kind: Pod
apiVersion: v1
metadata:
  name: sriov-device-plugin
spec:
  containers:
  - name: sriov-device-plugin 
    image: nfvpe/sriov-device-plugin:release-v1
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sriovdp --logtostderr 10;" ]
    volumeMounts:
    - mountPath: /var/lib/kubelet/device-plugins/ 
      name: devicesock 
      readOnly: false
    - mountPath: /sys/class/net
      name: net
      readOnly: true
  volumes:
  - name: devicesock 
    hostPath:
     # directory location on host
     path: /var/lib/kubelet/device-plugins/
  - name: net
    hostPath:
      path: /sys/class/net
  hostNetwork: true
  hostPID: true
